<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Collaberas-MacBook-Pro.local" failures="1" tests="4" name="Demonstrating Assert" time="0.075" errors="0" timestamp="2023-04-19T11:39:20 PST">
  <testcase classname="TestNG_Exercise.TestNG_Assert" name="add" time="0.016">
    <failure type="java.lang.AssertionError" message="The addition result is incorrect expected [12] but found [8]">
      <![CDATA[java.lang.AssertionError: The addition result is incorrect expected [12] but found [8]
at TestNG_Exercise.TestNG_Assert.add(TestNG_Assert.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- add -->
  <testcase classname="TestNG_Exercise.TestNG_Assert" name="multiplication" time="0.004"/>
  <testcase classname="TestNG_Exercise.TestNG_Assert" name="subtract" time="0.001"/>
  <testcase classname="TestNG_Exercise.TestNG_Assert" name="testDivision" time="0.003"/>
</testsuite> <!-- Demonstrating Assert -->
